package com.adnanjelic.simpletvstreamingapp.featurehome.ui.model

import com.adnanjelic.simpletvstreamingapp.featurehome.ui.mapper.CategoryPresentationToUiModelMapper
import com.adnanjelic.simpletvstreamingapp.featurehome.ui.mapper.HomeInfoPresentationDestinationToNavigationDestinationModelMapper
import com.adnanjelic.simpletvstreamingapp.featurehome.ui.mapper.HomeNotificationPresentationToUiModelMapper
import javax.inject.Inject

class HomeScreenDependencies @Inject constructor(
    val categoriesMapper: CategoryPresentationToUiModelMapper,
    val destinationMapper: HomeInfoPresentationDestinationToNavigationDestinationModelMapper,
    val notificationMapper: HomeNotificationPresentationToUiModelMapper
)
